name: Publish Content

on:
  push:
    branches:
      - main
      - 'preview/*'
    paths:
      - 'posts/**'
      - '*.md'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get commit SHA
        id: sha
        run: echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Trigger webhook
        run: |
          PAYLOAD=$(cat <<EOF
          {
            "sha": "${{ steps.sha.outputs.sha }}",
            "repository": {
              "full_name": "${{ github.repository }}"
            },
            "head_commit": {
              "id": "${{ steps.sha.outputs.sha }}",
              "message": "${{ github.event.head_commit.message }}"
            }
          }
          EOF
          )

          SIGNATURE="sha256=$(echo -n "$PAYLOAD" | openssl dgst -sha256 -hmac "${{ secrets.WEBHOOK_SECRET }}" | cut -d' ' -f2)"

          curl -X POST \
            -H "Content-Type: application/json" \
            -H "X-Signature-256: $SIGNATURE" \
            -d "$PAYLOAD" \
            "${{ secrets.WEBHOOK_URL }}/webhook/publish"
